version: '3.8'
services:

        sonarqube:
                # container_name: db        // not supported by 'docker stack deploy'
                image: sonarqube:lts-community
                restart: unless-stopped
                environment:
                    - SONARQUBE_JDBC_USERNAME=sonar_db_user
                    - SONARQUBE_JDBC_PASSWORD=password
                    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-postgresql:5432/sonarqube_database
                ports:
                        - "9000:9000"
                        - "9092:9092"
                volumes:
                       - sonarqube_conf:/opt/sonarqube/conf
                       - sonarqube_data:/opt/sonarqube/data
                       - sonarqube_extensions:/opt/sonarqube/extensions
                       - sonarqube_logs:/opt/sonarqube/logs
                

        sonar-postgresql: 
                image: postgres:14.1
                restart: unless-stopped
                environment:
                    - POSTGRES_USER=sonar_db_user
                    - POSTGRES_PASSWORD=password
                    - POSTGRES_DB=sonarqube_database     
                volumes: 
                      - sonarqube_db:/var/lib/postgresql
                      - sonarqube_postgresql_data:/var/lib/postgresql/data

volumes: 
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    sonarqube_db:
    sonarqube_postgresql_data:

